# Index dédié aux écritures CSV/Finance
name: idx-finance-csv
query:
  type: simple                # souvent suffisant pour champs structurés
select:
  - row_id
  - Date
  - N_Piece
  - Client
  - Ville
  - Nature
  - Compte
  - Montant_HT
  - TVA_20
  - Montant_TTC
  - Compte_Tiers
answers:
  enabled: false
captions:
  enabled: false
filters_supported:
  - eq
  - any_in
  - tenant_id
defaults:
  top: 50
